name: Splunk App CI/CD
on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
permissions:
  pull-requests: write
  actions: write
  checks: write
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
      checks: write
    steps:
      - name: Run Splunk App CI/CD
        uses: livehybrid/splunk-app-cicd-action@main
        with:
          python-version: "3.9"
          included-tags: "cloud,private_victoria,future"
          splunkbase-username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase-password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  
  #     - name: Upload Reports
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: AppInspect_response.html
  #         path: AppInspect_response.html

  # publish-gh:
  #   needs:
  #     - appinspectapi
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   container: cimg/go:1.19
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: .
  #     - uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: "dist/*"
  #         allowUpdates: true
